fix bowtie2
If fasq.qz files are used with bowtie and the option `fifo: true`
then bowtie2 still fails (sometimes) with:
```
Error: reads file does not look like a FASTQ file

  terminate called after throwing an instance of ''int''

  Aborted

  (ERR): bowtie2-align exited with value 134
```
The reason is a raice condition in vanilla bowtie2 that can make
the fifo untreadale at times:
http://seqanswers.com/forums/showthread.php?t=16540
There is a patched version of bowtie that supposedly works
with fifo inoput: https://github.com/earonesty/bowtie